version: "3.9"

services:
  api:
    build: .
    container_name: payping-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payping-api.rule=Host(`paypingai.com`) || Host(`www.paypingai.com`)"
      - "traefik.http.routers.payping-api.entrypoints=web"
      - "traefik.http.services.payping-api.loadbalancer.server.port=8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  celery-worker:
    build: .
    container_name: payping-celery
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    build: .
    container_name: payping-flower
    command: celery -A app.celery_app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payping-flower.rule=Host(`flower.paypingai.com`)"
      - "traefik.http.routers.payping-flower.entrypoints=web"
      - "traefik.http.services.payping-flower.loadbalancer.server.port=5555"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  batch-generate-recurring-invoices:
    build: .
    container_name: payping-batch-generate-recurring-invoices
    command: python batch_jobs/generate_recurring_invoices.py
    env_file:
      - .env
    depends_on:
      - redis
    restart: "no"

  batch-otp-cleanup-job:
    build: .
    container_name: payping-batch-otp-cleanup-job
    command: python batch_jobs/delete_old_otps.py
    env_file:
      - .env
    depends_on:
      - redis
    restart: "no"

  redis:
    image: redis:7-alpine
    container_name: payping-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  traefik:
    image: traefik:v3.6
    container_name: payping-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped


